[workspace]
resolver = "2"
members = [
    "rust-common",
    "rust-components/*"
]

[workspace.dependencies]
teloxide = { version = "0.12", features = ["macros"] }
log = "0.4"
pretty_env_logger = "0.5"
tokio = "1"
serde = "1"
