version: "3.8"

name: pegasus-bot

networks:
  app-network:
    driver: bridge

volumes:
  logs:
    driver: local
  postgres-data:
    driver: local
  redis-data:
    driver: local
  etcd-data:
    driver: local
  consul-data:
    driver: local

services:
  jaeger:
    image: jaegertracing/all-in-one:latest
    ports:
      - "4317:4317"
      - "16686:16686"
    networks:
      - app-network

  postgres:
    image: postgres:15-alpine
    environment:
      - POSTGRES_USER=pegasus
      - POSTGRES_PASSWORD=pegasus
      - POSTGRES_DB=pegasus
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - app-network

  redis:
    image: redis:latest
    environment:
      - REDIS_PASSWORD=cecilia
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - app-network

  mq:
    image: rabbitmq:management-alpine
    environment:
      - RABBITMQ_DEFAULT_USER=pegasus
      - RABBITMQ_DEFAULT_PASS=pegasus
    ports:
      - "15672:15672"
      - "5672:5672"
    networks:
      - app-network

  etcd:
    image: quay.io/coreos/etcd:v3.5.9-arm64
    entrypoint: /usr/local/bin/etcd
    command:
      - --name=etcd
      - --data-dir=/etcd_data
      - --initial-advertise-peer-urls=http://etcd:2380
      - --listen-peer-urls=http://0.0.0.0:2380
      - --listen-client-urls=http://0.0.0.0:2379
      - --advertise-client-urls=http://etcd:2379
      - --initial-cluster-token=etcd-cluster-1
      - --initial-cluster=etcd=http://etcd:2380
      - --initial-cluster-state=new
      - --heartbeat-interval=250
      - --election-timeout=1250
      - --experimental-enable-distributed-tracing=true
      - --experimental-distributed-tracing-address='jaeger:4317'
    ports:
      - "2379:2379"
      - "2380:2380"
    networks:
      - app-network
    volumes:
      - etcd-data:/etcd_data

  consul:
    image: consul:1.15
    ports:
      - "8500:8500"
    volumes:
      - consul-data:/consul/data
    networks:
      - app-network
