version: "3.8"

name: pegasus-bot

networks:
  pegasus-network:
    driver: bridge
    external: true

services:
  bot-api-server:
    image: aiogram/telegram-bot-api
    environment:
      TELEGRAM_API_ID: ""
      TELEGRAM_API_HASH: ""
    ports:
      - "8081:8081"
    networks:
      - pegasus-network

  gateway:
    image: pegasus-bot/gateway
    build:
      context: .
      dockerfile: docker/basic/Dockerfile
      args:
        COMPONENT: "gateway"
    ports:
      - "8080:8080"
    networks:
      - pegasus-network
    env_file:
      - .env

  basic-handler:
    image: pegasus-bot/basic-handler
    build:
      context: .
      dockerfile: docker/basic/Dockerfile
      args:
        COMPONENT: "basic-handler"
    deploy:
      replicas: 3
    networks:
      - pegasus-network
    env_file:
      - .env

  remake-handler:
    image: pegasus-bot/remake-handler
    build:
      context: .
      dockerfile: docker/basic/Dockerfile
      args:
        COMPONENT: "remake-handler"
    deploy:
      replicas: 3
    networks:
      - pegasus-network
    env_file:
      - .env

  network-functions-handler:
    image: pegasus-bot/network-functions-handler
    build:
      context: .
      dockerfile: docker/rust-basic/Dockerfile
      args:
        COMPONENT: "network-functions-handler"
    deploy:
      replicas: 3
    networks:
      - pegasus-network
    env_file:
      - .env
    environment:
      RUST_LOG: "info"
