version: "3.8"

name: pegasus-bot-env

networks:
  pegasus-network:
    driver: bridge
    external: true

volumes:
  logs:
    driver: local
  postgres-data:
    driver: local
  redis-data:
    driver: local

services:
  jaeger:
    image: jaegertracing/all-in-one:latest
    ports:
      - "4317:4317"
      - "16686:16686"
    networks:
      - pegasus-network

  postgres:
    image: postgres:15-alpine
    environment:
      - POSTGRES_USER=pegasus
      - POSTGRES_PASSWORD=pegasus
      - POSTGRES_DB=pegasus
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - pegasus-network

  redis:
    image: redis:latest
    environment:
      - REDIS_PASSWORD=pegasus
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - pegasus-network

  mq:
    image: rabbitmq:management-alpine
    environment:
      - RABBITMQ_DEFAULT_USER=pegasus
      - RABBITMQ_DEFAULT_PASS=pegasus
    ports:
      - "15672:15672"
      - "5672:5672"
    networks:
      - pegasus-network
