[package]
name = "pegasus-common"
version = "0.1.0"
edition = "2021"

[lib]
name = "pegasus_common"
path = "src/lib.rs"

[dependencies]
serde = { workspace = true, features = ["derive"] }
serde_yaml = "0.9"
