name: Docker Release

on:
  push:
    tags:
      - '*'
  workflow_dispatch:

jobs:
  prepare-components:
    name: Prepare Components
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install jq
        run: sudo apt-get install jq

      - name: Get Components
        id: get-components
        shell: bash
        run: |
          COMPONENTS=$(ls components)
          JSON_STRING=$(jq -nr --arg items "$COMPONENTS" '$items | split("\n") | map(select(length > 0)) | {components: .}')
          echo 'components=<<EOF' >> $GITHUB_OUTPUT
          echo "$JSON_STRING" >> $GITHUB_OUTPUT
          echo 'EOF' >> $GITHUB_OUTPUT

  build:
    name: Build
    runs-on: ubuntu-latest

    needs:
      - prepare-components

    strategy:
      fail-fast: false
      matrix: ${{ fromJson(needs.prepare-components.outputs.components) }}

    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ghcr.io/${{ github.repository }}/pegasus-${{ matrix.components }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: docker/basic/Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          args: COMPONENT=${{ matrix.components }}
